#!/usr/bin/env php
<?php

use Phalyfusion\Console\Command\AnalyseCommand;
use Symfony\Component\Console\Application;

$possibleFiles = [__DIR__.'/../../autoload.php', __DIR__.'/../autoload.php', __DIR__.'/vendor/autoload.php'];
$file = null;
foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;

        break;
    }
}

if (null === $file) {
    throw new RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

unset($possibleFiles, $possibleFile, $file);

$rootDir = __DIR__;

$application = new Application('Phalyfusion', '1.0.0');
$command = new AnalyseCommand($rootDir);

$application->add($command);
$application->setDefaultCommand($command->getName(), false);
$application->run();
